model:
  type: wresnet28_2
dataset: cifar10
aug: ua_uasesp
cutout: 16
batch: 128
gpus: 1
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
augmentation_search_space: uniaug_space
augmentation_parameter_max: 30
