model:
  type: miniconvnet
dataset: cifar10
aug: ta_fixedsesp
cutout: 16
batch: 128
gpus: 1
epoch: 400
lr: 0.1
lr_schedule:
  type: 'cosine'
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
augmentation_search_space: fixed_standard
augmentation_parameter_max: 30
